### ISSUE TITLE
[computer-use-demo] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by aristideubertas** [anthropics/claude-quickstarts#43]
![image](https://github.com/user-attachments/assets/5b32039a-1cbe-4740-8adb-483421063550)

When typing in the first command, I received this error straight away. Docker container starts fine without errors beforehand. 

Using bedrock with aws configured.

Error log:
`➡️  Open http://localhost:8080 in your browser to begin
2024-10-22 16:59:18.699 Uncaught app exception
Traceback (most recent call last):
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/computeruse/computer_use_demo/streamlit.py", line 364, in <module>
    asyncio.run(main())
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/computeruse/computer_use_demo/streamlit.py", line 220, in main
    st.session_state.messages = await sampling_loop(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/computeruse/computer_use_demo/loop.py", line 127, in sampling_loop
    for content_block in cast(list[BetaContentBlock], response.content):
TypeError: 'NoneType' object is not iterable
`

**Comment by nsmccandlish** [comment]
This should work now!

**Comment by aristideubertas** [comment]
Still happening with image 20034c0aa8c95a7e589035e139686f226ec088d12f5c69b9b9f2da6d9bdcf5e4

**Comment by x5a** [comment]
@aristideubertas I'm closing this out as I believe we have fixed this - it was an SDK bug fixed in the [latest release](https://github.com/anthropics/anthropic-sdk-python/tree/v0.37.1), specific to Bedrock/Vertex
