### ISSUE TITLE
APIConnectionError: Connection error.

### ISSUE THREAD

**Issue by TechieHank** [anthropics/claude-quickstarts#85]
I have installed the docker image and I have tested that my via curl and my API key can talk to Anthropic. When I run the docker container, noVNC starts and I can even browse the web, but when I run a prompt for the API to work, I get this error message:

File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "/home/computeruse/computer_use_demo/streamlit.py", line 357, in <module>
    asyncio.run(main())
File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
File "/home/computeruse/computer_use_demo/streamlit.py", line 213, in main
    st.session_state.messages = await sampling_loop(
                                ^^^^^^^^^^^^^^^^^^^^

Thanks in advance for guidance on how to fix this issue.

**Comment by TechieHank** [comment]
![Screenshot 2024-10-23 at 10 52 14 AM](https://github.com/user-attachments/assets/8a981acd-4f7c-4ead-ab4b-949b4ade6b69)

**Comment by rvadhavk** [comment]
I had the same error message and found more info in the logs in terminal where I started the container:
`httpx.LocalProtocolError: Illegal header value b'<REDACTED> '`

Turns out I had a trailing space when I pasted my API key.

**Comment by TechieHank** [comment]
@rvadhavk - Thanks for the feedback. I prune all my containers from docker and re-ran bash script without any trailing spaces. Unfortunately - the same issue is happening :( - I did tried to do a `sudo apt-get update` inside the docker container and it started complaining about a certificate.

![Screenshot 2024-10-23 at 5 48 02 PM](https://github.com/user-attachments/assets/14508f46-9cd7-4dc0-a71e-152cad9f831e)

**Comment by x5a** [comment]
@TechieHank are you on a network that has a firewall/proxy that re-encrypts traffic?

Regardless, I updated the latest image with a more verbose error log - can you post the traceback after doing a `docker pull ghcr.io/anthropics/computer-use-demo:latest` and restarting your container?

**Comment by moody-dunamu** [comment]
Are you using an intranet?
I may have the same problem as you, but I also had a Connection Error and the problem was with the certificate. So I updated the certificate and it was fixed.

**Comment by moody-dunamu** [comment]
Are you using an intranet?
I may have the same problem as you, but I also had a Connection Error and the problem was with the certificate. So I updated the certificate and it was fixed.

**Comment by moo1o** [comment]
Are you using an intranet?
I may have the same problem as you, but I also had a Connection Error and the problem was with the certificate. So I updated the certificate and it was fixed.

**Comment by TechieHank** [comment]
> @TechieHank are you on a network that has a firewall/proxy that re-encrypts traffic?
> 
> Regardless, I updated the latest image with a more verbose error log - can you post the traceback after doing a `docker pull ghcr.io/anthropics/computer-use-demo:latest` and restarting your container?

@x5a - Here's the Traceback after doing an update of the image:


File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 152, in start_tls
    with map_exceptions(exc_map):

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc

httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 990, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc

httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/computeruse/computer_use_demo/loop.py", line 132, in sampling_loop
    raw_response = client.beta.messages.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_legacy_response.py", line 377, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/resources/beta/messages/messages.py", line 896, in create
    return self._post(
           ^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1014, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1014, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1024, in _request
    raise APIConnectionError(request=request) from err

anthropic.APIConnectionError: Connection error.

**Comment by TechieHank** [comment]
> Are you using an intranet? I may have the same problem as you, but I also had a Connection Error and the problem was with the certificate. So I updated the certificate and it was fixed.

Thanks for the feedback @moo1o - What command did you use to update it? I assume you did the update inside the container Debian VM?

**Comment by moo1o** [comment]
@TechieHank 
I succeeded by following the steps below.
1. Access api.anthropic.com, check the valid certificate information, and extract it.
2. Check the certificate location on your PC with pip show certifi.
3. In the certificate location, paste the certificate information extracted in step 1 at the end of the cacerti.pem file.

**Comment by my-other-github-account** [comment]
Having a somewhat similar error while using the Docker container, but it only occurs intermittently, and I can rerun in the same container and it starts working again - so isn't a general failure. Any idea why this might only happen intermittently, and what I can do to fix it for the Docker container?

```
File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc

httpcore.ReadError: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2580)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 990, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc

httpx.ReadError: [SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2580)


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/home/computeruse/computer_use_demo/loop.py", line 132, in sampling_loop
    raw_response = client.beta.messages.with_raw_response.create(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_legacy_response.py", line 377, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/resources/beta/messages/messages.py", line 896, in create
    return self._post(
           ^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1277, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 954, in request
    return self._request(
           ^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1014, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1014, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1092, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^

  File "/home/computeruse/.pyenv/versions/3.11.6/lib/python3.11/site-packages/anthropic/_base_client.py", line 1024, in _request
    raise APIConnectionError(request=request) from err

anthropic.APIConnectionError: Connection error.
```

**Comment by JosePortoMonokera** [comment]
Guys... I tried everything without sucess. having the same error. Seems to be a problem with the container.

**Comment by hongyu-presight** [comment]
> 1. certificate
i encounter the same error as yours

**Comment by vadim-su** [comment]
Same error, tried using solution from this thread but nothing works

**Comment by TechKemon** [comment]
same error today

**Comment by XMan-CN-SG-JP** [comment]
Same error today

**Comment by carrot-codeing** [comment]
Same error by anthoripic sdk，but works well in openai sdk

**Comment by JuanCS-Dev** [comment]
## Root Cause: Network/DNS Issues Inside Container

Your API key works (verified with curl), but the Python client inside Docker can't reach `api.anthropic.com`.

### Step-by-Step Diagnosis

**1. Test DNS resolution:**
```bash
docker exec [container-id] nslookup api.anthropic.com
```

Expected: IP address(es) returned  
If it fails: DNS issue (see Fix 1)

**2. Test HTTPS connectivity:**
```bash
docker exec [container-id] curl -v https://api.anthropic.com/v1/messages \
  -H "x-api-key: $ANTHROPIC_API_KEY" \
  -H "anthropic-version: 2023-06-01" \
  -H "content-type: application/json" \
  -d '{"model":"claude-3-5-sonnet-20241022","max_tokens":10,"messages":[{"role":"user","content":"test"}]}'
```

Expected: JSON response (even an error is fine)  
If it times out: Network/firewall issue (see Fix 2-4)

**3. Check Python SSL certificates:**
```bash
docker exec [container-id] python3 -c "import ssl; print(ssl.get_default_verify_paths())"
```

### Fixes

**Fix 1: DNS Resolution (Most Common)**
```bash
docker run \
  --dns 8.8.8.8 \
  --dns 1.1.1.1 \
  -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
  -p 5900:5900 -p 6080:6080 -p 8080:8080 -p 8501:8501 \
  computer-use-demo
```

**Fix 2: Corporate Proxy**

If you're behind a corporate proxy:
```bash
docker run \
  -e HTTP_PROXY=http://proxy.company.com:8080 \
  -e HTTPS_PROXY=http://proxy.company.com:8080 \
  -e NO_PROXY=localhost,127.0.0.1 \
  -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
  -p 5900:5900 -p 6080:6080 -p 8080:8080 -p 8501:8501 \
  computer-use-demo
```

**Fix 3: IPv6 Disabled But Container Tries It**

Add to docker-compose.yml:
```yaml
services:
  computer-use-demo:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
```

Or use flag:
```bash
docker run --sysctl net.ipv6.conf.all.disable_ipv6=1 [other-flags] computer-use-demo
```

**Fix 4: Host Network Mode (Nuclear Option)**
```bash
docker run \
  --network host \
  -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
  computer-use-demo
```

Note: With host mode, access via `http://localhost:8080` directly (ports auto-shared).

**Fix 5: SSL Certificate Issue**

If curl works but Python fails with SSL errors:
```dockerfile
# Add to Dockerfile before final RUN
RUN pip install --upgrade certifi
```

### Validation

After applying fix, test end-to-end:
```bash
docker exec [container-id] python3 -c "
import anthropic
client = anthropic.Anthropic(api_key='$ANTHROPIC_API_KEY')
message = client.messages.create(
    model='claude-3-5-sonnet-20241022',
    max_tokens=10,
    messages=[{'role': 'user', 'content': 'test'}]
)
print('SUCCESS:', message.content)
"
```

If this works, Streamlit will work too.

### Which Fix Should You Try First?

- **Home/normal network**: Try Fix 1 (DNS)
- **Company laptop**: Try Fix 2 (proxy)
- **Weird network (hotel/airport)**: Try Fix 4 (host mode)
- **VPN active**: Disconnect VPN and retry, or use Fix 4

Let me know what `nslookup` and `curl` show - I can narrow it down further.

**Comment by Qlexio** [comment]
Hello,
I had the same kind of connection issue.

This was due to Anthropic environment variables conflicts between my `.env` file and the ones loaded by the Shell.

In this case particularly, I just had to delete the following ones in my Python session (changes are only done inside the Python env): 
* `ANTHROPIC_AUTH_TOKEN`
* `ANTHROPIC_BASE_URL`

```
import os


del os.environ["ANTHROPIC_AUTH_TOKEN"]
del os.environ["ANTHROPIC_BASE_URL"]

# Your script here
```
